### ISSUE TITLE
Update Accessor models to reflect 08/12 meeting

### ISSUE THREAD

**Issue by audsc** [knowmetools/km-api#157]
### Feature Proposal

We decided to remove individual profile access and distinguish between 'followers' and 'admin' access privileges. 

- 'Followers' only have read access to public pages. 
- 'Admin' have read and write access to all pages.

In order to reflect this, we plan to get rid of the `ProfileAccess` model and add an `isAdmin` field to the `KMUserAccess` model.

- [ ] add an isAdmin field to the `KMUserAccess` model
- [ ] get rid of `ProfileAccess` model

**Comment by audsc** [comment]
We double checked the [proposed access model](https://docs.google.com/spreadsheets/d/1vARlVr8eUiSZRUOY-xoSYvj6FFA1IGwAquuFmpGrca4/edit#gid=0) with Susan, and we will be moving forward implementing it.

**Comment by audsc** [comment]
Instead of replacing can_read_everywhere and can_write_everywhere with is_admin, would it make sense to keep them incase the access model changes down the road? 
(essentially, is_admin = can_read_everywhere AND can_write_everywhere) @cdriehuys

**Comment by cdriehuys** [comment]
I think it makes sense for the fields to describe the action they allow, rather than an arbitrary name like 'admin'. To clarify, I prefer fields like `can_write`. I don't think we need the 'everywhere' suffix since we aren't supporting access to specific profiles. Also, we don't need the `can_read` field since the presence of ` KMUserAccessor` instance implicitly grants read permissions.

**Comment by cdriehuys** [comment]
We have decided on `has_private_profile_access`.

**Comment by cdriehuys** [comment]
I believe all the issues raised here have been addressed. Updating the fields on the `KMUserAccessor` model is handled in #163 and deletion of the `ProfileAccessor` model is handled in #162.
