### ISSUE TITLE
Cannot Unfollow Users

### ISSUE THREAD

**Issue by Brandogs** [knowmetools/km-api#358]
### Bug Report

Trying to delete at /know-me/accessors/{id}/ for accessors returned from /know-me/accessors/accepted/  throws a 403 error.

**Comment by cdriehuys** [comment]
When we inevitably get hit by a similar issue in the future, the root cause is that the package we use to enforce permissions has more granular controls for views inheriting from `ViewSet`, but not `GenericAPIView`. To get around this, we added a custom view mixin from dbkaplan/dry-rest-permissions#39 (see [this comment](https://github.com/dbkaplan/dry-rest-permissions/issues/39#issuecomment-287345071) in particular) that attaches an `action` attribute to the view, which allows us to specify permissions based on request type.
