### ISSUE TITLE
Remove extra profile row types

### ISSUE THREAD

**Issue by cdriehuys** [knowmetools/km-api#66]
From the mockups we received, it looks like we will only have text rows and visual rows. No grouped or one-at-a-time rows.

One question this brings up is how do we handle migrating existing data? Do we just drop rows that have the old type?

[Profile Preview Overview.pdf](https://github.com/knowmetools/km-api/files/1162910/Profile.Preview.Overview.pdf)

**Comment by Brandogs** [comment]
One-at-a-time rows will migrate fairly smoothly to Header rows.

We have discussed three options for category rows:
1) Categories become Lists - this could be problematic because items in a list would lose information in the Profile Item such a the Gallery attachements
2) Categories become Profile Topics - For other Profile Row types, Rows have a 1-to-1 mapping with ProfileTopics. In this scenario, we would split up Profile Rows into multiple Topics based on their category.
3) Remove all reference to Category and simply migrate to a ProfileTopic - If this is done, categories such as "Likes" and "Dislikes" would get bunched together, losing the meaning and purpose of the row in the first place.

**Comment by cdriehuys** [comment]
Suggestion 2 sounds like our best option. It has been added to the discussion on migration in #69.

**Comment by audsc** [comment]
It seems that `Categories` has already been eliminated from the code base. Am I missing something?

**Comment by cdriehuys** [comment]
The concerns about migrating existing data are more relevant for when we start migrating over data from the old backend. For now, all we have to do is remove paged rows and grouped rows as choices from the `ProfileTopic` model.
