### ISSUE TITLE
Improve error message when logging in with an unverified email

### ISSUE THREAD

**Issue by Brandogs** [knowmetools/km-api#70]
When a user tries to sign up with an email address that is unverified, it simply says the account already exists. This message should mention something about the account still requiring verification, and possibly send a new verification email since these emails expire.

**Comment by cdriehuys** [comment]
First a clarification: By "sign up" do you mean "log in"? I'll assume you mean log in.

This functionality was lost when we implemented #54. I see two possible solutions here.

### Raising an error when authenticating

The [section of the docs](https://docs.djangoproject.com/en/1.11/topics/auth/customizing/#specifying-authentication-backends) describing how the authentication backends are checked mentions raising a `PermissionError`. This immediately causes authentication to fail, which is what we want. It's just a question of if we can get access to why the authentication failed so that we can present that message to the user.

### Explicitly checking for an unverified email if authentication fails

In the token request serializer, if authentication fails, we could specifically check if the email address is unverified. I feel that this would be duplicating logic a little bit from the authentication backend, so I would prefer the first solution.

**Comment by cdriehuys** [comment]
As for your question about automatically resending a verification email, I would like to move that discussion to #72.

**Comment by cdriehuys** [comment]
It looks like the built in `authenticate` method swallows any `PermissionDenied` exceptions and just returns `None`. This means we will need a specific check for an unverified email.

**Comment by cdriehuys** [comment]
This check would be easier to add if we reverted #60.

**Comment by audsc** [comment]
Looks good! @Brandogs do you agree?
